In [77]:
import torch

# random_state in C (check vit.c)-> 69
# CLS+Patch Embeddings (5 x 4)
cls_patch_embeddings = torch.tensor([
    [0.7825, 1.0174,   1.6778,   1.2251],
    [3.3223, 2.8748, 3.0050, 3.2986],
    [3.3452, 2.4302, 3.0276, 2.3968],
    [3.0843, 3.1493, 2.6917, 3.3506],
    [3.5323, 3.3369, 2.9087, 2.9229]
])

In [78]:
# Given matrix as a flat list
qkv_multihead_blocks = [
    [0.2771, 0.9177, 0.6750, 0.4321, 0.9526, 0.5549],
    [0.6051, 0.9398, 0.2410, 0.8902, 0.0560, 0.6765],
    [0.3281, 0.9908, 0.2155, 0.6071, 0.4933, 0.1080],
    [0.5215, 0.7952, 0.1658, 0.4366, 0.8078, 0.2068],
    [0.2136, 0.3869, 0.1732, 0.7026, 0.3515, 0.9694],
    [0.2413, 0.6287, 0.8870, 0.9163, 0.0608, 0.8397],
    [0.4712, 0.6659, 0.7795, 0.7121, 0.5561, 0.8354],
    [0.3886, 0.8843, 0.8263, 0.6041, 0.4914, 0.3195],
    [0.7120, 0.0129, 0.1147, 0.8778, 0.4495, 0.9225],
    [0.0846, 0.6631, 0.3095, 0.2578, 0.3657, 0.6610],
    [0.2271, 0.6070, 0.2896, 0.1141, 0.5233, 0.3505],
    [0.9538, 0.9945, 0.0164, 0.7332, 0.7066, 0.5725],
    [0.5687, 0.0952, 0.4567, 0.3949, 0.6993, 0.9481],
    [0.7145, 0.4113, 0.9610, 0.8292, 0.2892, 0.4106],
    [0.7517, 0.3738, 0.0736, 0.0612, 0.6315, 0.4393],
    [0.7222, 0.8586, 0.0463, 0.0118, 0.9728, 0.5696]
]

# Convert to tensor
tensor = torch.tensor(qkv_multihead_blocks)
# Reshape into (Blocks=2, Heads=2, Head_Size=4, QKV=6)
tensor = tensor.view(2, 2, 4, 6)
print(tensor.shape)  # Should output torch.Size([2, 2, 4, 6])
print(tensor)

torch.Size([2, 2, 4, 6])
tensor([[[[0.2771, 0.9177, 0.6750, 0.4321, 0.9526, 0.5549],
          [0.6051, 0.9398, 0.2410, 0.8902, 0.0560, 0.6765],
          [0.3281, 0.9908, 0.2155, 0.6071, 0.4933, 0.1080],
          [0.5215, 0.7952, 0.1658, 0.4366, 0.8078, 0.2068]],

         [[0.2136, 0.3869, 0.1732, 0.7026, 0.3515, 0.9694],
          [0.2413, 0.6287, 0.8870, 0.9163, 0.0608, 0.8397],
          [0.4712, 0.6659, 0.7795, 0.7121, 0.5561, 0.8354],
          [0.3886, 0.8843, 0.8263, 0.6041, 0.4914, 0.3195]]],


        [[[0.7120, 0.0129, 0.1147, 0.8778, 0.4495, 0.9225],
          [0.0846, 0.6631, 0.3095, 0.2578, 0.3657, 0.6610],
          [0.2271, 0.6070, 0.2896, 0.1141, 0.5233, 0.3505],
          [0.9538, 0.9945, 0.0164, 0.7332, 0.7066, 0.5725]],

         [[0.5687, 0.0952, 0.4567, 0.3949, 0.6993, 0.9481],
          [0.7145, 0.4113, 0.9610, 0.8292, 0.2892, 0.4106],
          [0.7517, 0.3738, 0.0736, 0.0612, 0.6315, 0.4393],
          [0.7222, 0.8586, 0.0463, 0.0118, 0.9728, 0.5696]]]])


In [86]:
block = 1
head = 0
Q,K,V = tensor[:,:,:,:2], tensor[:,:,:,2:4], tensor[:,:,:,4:]

In [93]:
Q_out = cls_patch_embeddings@Q
K_out = cls_patch_embeddings@K
V_out = cls_patch_embeddings@V

In [94]:
def print_info(mat, name):
    print(name, mat.shape)
    print(mat, "\n\n")

In [95]:
print_info(Q_out, "Query Result: ")
print_info(K_out, "Key Result: ")
print_info(V_out, "Value Result: ")

Query Result:  torch.Size([2, 2, 5, 2])
tensor([[[[ 2.0218,  4.3108],
          [ 5.3663, 11.3510],
          [ 4.6408, 10.2595],
          [ 5.3908, 11.1215],
          [ 5.4766, 11.5838]],

         [[ 1.6793,  3.1430],
          [ 4.1011,  8.0108],
          [ 3.6589,  6.9577],
          [ 3.9891,  7.9286],
          [ 4.0661,  7.9862]]],


        [[[ 2.1927,  2.9215],
          [ 6.4373,  7.0536],
          [ 5.5610,  5.8760],
          [ 6.2695,  7.0941],
          [ 6.2457,  6.9307]],

         [[ 3.3179,  2.1720],
          [ 8.5845,  5.4541],
          [ 7.6456,  4.5076],
          [ 8.4474,  5.4719],
          [ 8.6904,  5.3056]]]]) 


Key Result:  torch.Size([2, 2, 5, 2])
tensor([[[[1.3381, 2.7973],
          [4.1299, 7.2592],
          [3.8935, 6.4933],
          [3.9765, 7.2332],
          [4.2999, 7.5388]],

         [[3.3581, 3.4169],
          [8.1934, 9.1010],
          [7.0755, 8.1810],
          [8.1944, 8.9936],
          [8.2541, 9.3764]]],


        [[[0.9106, 2.0

In [91]:
import torch

def simplified_attention(Q, K, V):
    d_k = Q.shape[-1]
    attn_scores = torch.matmul(Q, K.transpose(-2, -1)) 
    attn_scores = attn_scores / torch.sqrt(torch.tensor(d_k, dtype=torch.float32))
    attn_weights = torch.softmax(attn_scores, dim=-1) 
    attn_output = torch.matmul(attn_weights, V)

    return attn_output

# Outputs from all blocks

In [92]:
simplified_attention(Q_out, K_out.T, V_out)

tensor([[[[7.3345, 5.0054],
          [7.3495, 5.1113],
          [7.3494, 5.1024],
          [7.3495, 5.1103],
          [7.3495, 5.1127]],

         [[4.5149, 9.3462],
          [4.5112, 9.4877],
          [4.5129, 9.4647],
          [4.5114, 9.4858],
          [4.5112, 9.4871]]],


        [[[6.3548, 7.9389],
          [6.3978, 8.0339],
          [6.3936, 8.0190],
          [6.3979, 8.0328],
          [6.3975, 8.0317]],

         [[8.0987, 7.5714],
          [8.1141, 7.6516],
          [8.1135, 7.6453],
          [8.1141, 7.6513],
          [8.1141, 7.6516]]]])